/**
 * Utility functions for cleaning and sanitizing content generated by LLMs.
 */
import { getTopicFallbackImage } from '@/lib/services/image';

/**
 * Sanitizes HTML content from LLMs:
 * - Strips accidental markdown code fences (```html ... ```)
 * - Converts literal backslash escape sequences (\n, \r, \t) to actual whitespace/newlines
 * - Replaces double-escaped HTML quotes
 * - Normalizes image tags to modern 16:9 aspect-ratio and object-cover to prevent stretching
 * - Ensures every article has a valid, non-broken header image
 * - Removes empty paragraph tags
 */
export function sanitizeHtml(content: string, title?: string, type?: string): string {
  if (!content) return '';

  const fallbackImg = title ? getTopicFallbackImage(title, type) : 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&h=675&q=80';

  let cleaned = content
    // Remove markdown code fences if LLM wrapped HTML in ```html ... ```
    .replace(/^```(?:html)?\s*/i, '')
    .replace(/\s*```$/i, '')
    // Replace double-escaped quotes in HTML tags (e.g. src=\"...\" -> src="...")
    .replace(/\\"/g, '"')
    .replace(/\\'/g, "'")
    // Replace literal backslash escape sequences (\n, \r, \r\n, \t) with real characters
    .replace(/\\+r\\+n|\\+n|\\+r/g, '\n')
    .replace(/\\+t/g, ' ')
    // Replace deprecated/broken source.unsplash.com URLs
    .replace(
      /https?:\/\/source\.unsplash\.com\/(?:800x400\/\?)?([^"'\s>]+)/g,
      (_, query) => getTopicFallbackImage(decodeURIComponent(query), type)
    )
    // Remove empty paragraphs that might be created by line breaks
    .replace(/<p>\s*<\/p>/g, '')
    .trim();

  // Ensure image tags have proper classes to prevent stretching (16:9 ratio, object-cover)
  cleaned = cleaned.replace(/<img\s+([^>]*?)class="([^"]*?)"([^>]*?)>/gi, (_, before, cls, after) => {
    let updatedCls = cls;
    // Replace h-auto or fixed height with responsive 16:9
    updatedCls = updatedCls.replace(/h-\w+/g, '');
    if (!updatedCls.includes('object-cover')) updatedCls += ' object-cover';
    if (!updatedCls.includes('aspect-')) updatedCls += ' aspect-[16/9]';
    if (!updatedCls.includes('rounded-')) updatedCls += ' rounded-2xl';
    if (!updatedCls.includes('w-full')) updatedCls += ' w-full';
    if (!updatedCls.includes('shadow-')) updatedCls += ' shadow-lg';
    if (!updatedCls.includes('mb-')) updatedCls += ' mb-8';

    // Add client-side onerror fallback to prevent broken browser image icons
    const hasOnError = before.includes('onerror=') || after.includes('onerror=');
    const onErrorAttr = hasOnError ? '' : ` onerror="this.onerror=null;this.src='${fallbackImg}'"`;

    return `<img ${before}class="${updatedCls.trim()}"${onErrorAttr}${after}>`;
  });

  // If there's an img tag without a class attribute, add complete styling
  cleaned = cleaned.replace(/<img(?!\s+[^>]*?class=)([^>]*?)>/gi, (match, rest) => {
    const hasOnError = rest.includes('onerror=');
    const onErrorAttr = hasOnError ? '' : ` onerror="this.onerror=null;this.src='${fallbackImg}'"`;
    return `<img class="w-full aspect-[16/9] object-cover rounded-2xl shadow-lg mb-8"${onErrorAttr}${rest}>`;
  });

  // If an article has no image at all and a title is provided, prepend a fallback image
  if (title && !/<img[^>]+src=/i.test(cleaned)) {
    cleaned = `<img src="${fallbackImg}" alt="${title}" class="w-full aspect-[16/9] object-cover rounded-2xl shadow-lg mb-8" onerror="this.onerror=null;this.src='${fallbackImg}'" />\n` + cleaned;
  }

  return cleaned;
}

/**
 * Extracts a clean text snippet suitable for article cards and meta descriptions.
 * - Strips all HTML tags
 * - Eliminates literal and actual linebreaks/tabs
 * - Collapses whitespace to single spaces
 * - Truncates cleanly to maxLength
 */
export function getCleanSnippet(content: string, maxLength: number = 180): string {
  if (!content) return '';

  const cleanText = sanitizeHtml(content)
    .replace(/<[^>]*>?/gm, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  if (cleanText.length <= maxLength) {
    return cleanText;
  }

  return cleanText.substring(0, maxLength).trim() + '...';
}
