/**
 * Utility functions for cleaning and sanitizing content generated by LLMs.
 */

/**
 * Sanitizes HTML content from LLMs:
 * - Strips accidental markdown code fences (```html ... ```)
 * - Converts literal backslash escape sequences (\n, \r, \t) to actual whitespace/newlines
 * - Replaces deprecated Unsplash placeholder URLs with AI-generated Pollinations images
 * - Removes empty paragraph tags
 */
export function sanitizeHtml(content: string): string {
  if (!content) return '';

  return content
    // Remove markdown code fences if LLM wrapped HTML in ```html ... ```
    .replace(/^```(?:html)?\s*/i, '')
    .replace(/\s*```$/i, '')
    // Replace literal backslash escape sequences (\n, \r, \r\n, \t) with real characters
    // Matches \n, \\n, \\\n etc.
    .replace(/\\+r\\+n|\\+n|\\+r/g, '\n')
    .replace(/\\+t/g, ' ')
    // Replace deprecated/broken source.unsplash.com URLs
    .replace(
      /https?:\/\/source\.unsplash\.com\/(?:800x400\/\?)?([^"'\s>]+)/g,
      (_, query) =>
        `https://image.pollinations.ai/prompt/${encodeURIComponent(decodeURIComponent(query))}?width=800&height=400&nologo=true`
    )
    // Remove empty paragraphs that might be created by line breaks
    .replace(/<p>\s*<\/p>/g, '')
    .trim();
}

/**
 * Extracts a clean text snippet suitable for article cards and meta descriptions.
 * - Strips all HTML tags
 * - Eliminates literal and actual linebreaks/tabs
 * - Collapses whitespace to single spaces
 * - Truncates cleanly to maxLength
 */
export function getCleanSnippet(content: string, maxLength: number = 180): string {
  if (!content) return '';

  const cleanText = sanitizeHtml(content)
    .replace(/<[^>]*>?/gm, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  if (cleanText.length <= maxLength) {
    return cleanText;
  }

  return cleanText.substring(0, maxLength).trim() + '...';
}
