import Groq from 'groq-sdk';
import { sanitizeHtml } from '@/lib/utils/content';
import { getTopicImage } from '@/lib/services/image';

// We wrap initialization to avoid breaking Next.js build step when GROQ_API_KEY is not set.
// It will throw when actually executed if the key is missing in production.
const getGroqClient = () => {
  return new Groq({
    apiKey: process.env.GROQ_API_KEY || 'dummy-key-for-build',
  });
};

export async function generateContent(topic: string, type: 'trend' | 'niche'): Promise<{ title: string, content: string, slug: string }> {
  const groq = getGroqClient();
  try {
    // Resolve authentic, high-quality, unstretched header image
    const headerImageUrl = await getTopicImage(topic, type);

    let prompt = '';

    if (type === 'trend') {
      prompt = `Write a comprehensive, engaging, and SEO-optimized informational article about the current trending topic: "${topic}".
                Include a catchy title, a clear introduction, detailed body paragraphs, and a conclusion.
                Output the response in JSON format with exactly three fields: "title", "content" (in HTML format, ready to be displayed), and "slug" (a URL-friendly string derived from the title).
                CRITICAL: The HTML in "content" must be modern, using semantic tags (<h2>, <p>, <ul>, <li>). Do NOT include literal '\\n' strings or markdown code fences; format using standard HTML tags. Include this exact header image tag near the top of the article: <img src="${headerImageUrl}" alt="${topic}" class="w-full aspect-[16/9] object-cover rounded-2xl shadow-lg mb-8" />. Do NOT wrap the output in html/head/body tags.`;
    } else {
      prompt = `Write a comprehensive, bespoke care guide and informational page for the specific niche: "${topic}".
                Include a catchy title, a clear introduction, detailed body paragraphs (e.g., diet, exercise, temperament if it's an animal), and a conclusion.
                Output the response in JSON format with exactly three fields: "title", "content" (in HTML format, ready to be displayed), and "slug" (a URL-friendly string derived from the title).
                CRITICAL: The HTML in "content" must be modern, using semantic tags (<h2>, <p>, <ul>, <li>). Do NOT include literal '\\n' strings or markdown code fences; format using standard HTML tags. Include this exact header image tag near the top of the article: <img src="${headerImageUrl}" alt="${topic}" class="w-full aspect-[16/9] object-cover rounded-2xl shadow-lg mb-8" />. Do NOT wrap the output in html/head/body tags.`;
    }

    const chatCompletion = await groq.chat.completions.create({
      messages: [
        {
          role: "system",
          content: "You are an expert content creator and SEO specialist. Always output exactly valid JSON containing \"title\", \"content\", and \"slug\". The \"content\" field should contain well-formatted, beautiful HTML designed for modern styling with no literal '\\n' escape strings."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      model: process.env.GROQ_MODEL || "openai/gpt-oss-120b",
      temperature: 0.7,
      max_tokens: 3000,
      response_format: { type: "json_object" }
    });

    const result = chatCompletion.choices[0]?.message?.content;
    if (!result) {
      throw new Error("No content generated by Groq");
    }

    const parsedResult = JSON.parse(result);
    return {
      title: parsedResult.title,
      content: sanitizeHtml(parsedResult.content, parsedResult.title, type),
      slug: parsedResult.slug.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
    };

  } catch (error) {
    console.error('Error generating content with Groq:', error);
    throw error;
  }
}

export async function brainstormNiches(): Promise<string[]> {
  const groq = getGroqClient();
  try {
    const chatCompletion = await groq.chat.completions.create({
      messages: [
        {
          role: "system",
          content: "You are a creative brainstorming assistant. Output only a valid JSON array of strings containing your brainstormed topics."
        },
        {
          role: "user",
          content: "Generate a list of 10 specific, highly searched but relatively niche topics. For example, specific dog breeds, rare houseplants, niche hobbies, or specific tech tools. Output as a JSON array of strings named \"niches\"."
        }
      ],
      model: process.env.GROQ_MODEL || "openai/gpt-oss-120b",
      temperature: 0.8,
      max_tokens: 500,
      response_format: { type: "json_object" }
    });

    const result = chatCompletion.choices[0]?.message?.content;
    if (!result) return [];

    const parsed = JSON.parse(result);
    return parsed.niches || [];
  } catch (error) {
    console.error('Error brainstorming niches:', error);
    return [];
  }
}
